version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:8.9.1

jobs:
  lib-build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run:
        name: Install git
        command: |
          sudo apt-get install git coreutils
    - run: npm install
    - run:
        name: Sync Version
        command: |
          source ./.circleci/scripts/get-env.sh
          bash ./.circleci/scripts/sync-version.sh
    - run:
        name: Build lib
        command: bash ./.circleci/scripts/build-lib.sh

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-

    - persist_to_workspace:
        root: ~/repo
        paths:
          - .

  lib-deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: Deploy the lib
        command:  |
          source ./.circleci/scripts/get-env.sh
          bash ./.circleci/scripts/deploy-lib.sh

  github-page:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run:
        name: Install git
        command: |
          sudo apt-get install git coreutils
    - run: npm install
    - run:
        name: Build github-page
        command: npm run github-page

workflows:

  version: 2
  ngx-viacep:
    jobs:

    - lib-build:
        filters:
          branches:
            only:
              - develop
              - staging
              - master

    - lib-deploy:
        requires:
          - lib-build
        filters:
          branches:
            only:
              - develop
              - staging
              - master

    - github-page:
        filters:
          branches:
            only:
              - master
