version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults
    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install
    - run:
        name: Build lib
        command: npm run lib-build

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-

    - persist_to_workspace:
        root: ~/repo
        paths: .
#  deploy:
#    <<: *defaults
#    steps:
#    - attach_workspace:
#        at: ~/repo
#    - run:
#        name: Authenticate with registry
#        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
#    - run:
#        name: Publish package
#        command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /^[0-9]+.[0-9]+.[0-9]+$/
          branches:
            only:
              - rewrite
#    - deploy:
#        requires:
#        - test
#        filters:
#          tags:
#            only: /^[0-9]+.[0-9]+.[0-9]+$/
#          branches:
#            ignore: /.*/
